---
title: "EDA"
author: "Grace Liu"
date: "10/4/2018"
output: html_document
---

```{r tidyverse, include = FALSE}
library(tidyverse)
library(ggridges)
library(rnoaa)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2016-01-01",
                      date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, date, month, everything())
```

```{r}
weather_df %>%
  group_by(name, month) %>% 
  summarize(n = n())
```

```{r}
weather_df %>%
  group_by(name, month) %>% 
  summarize(number = n(),
            mean_tmax = mean(tmax, na.rm = TRUE),
            median_prcp = median(prcp, na.rm = TRUE),
            sd_tmin = sd(tmin, na.rm = TRUE)) %>%

ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point()
```

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  mutate(tmax_rank = min_rank(tmax)) %>% 
  filter(tmax_rank < 2)
```

