---
title: "Visualization Pt 1"
author: "Grace Liu"
date: "9/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r tidyverse, include = FALSE}
library(tidyverse)
library(ggridges)
```


```{r data_import, cache = TRUE}
library(rnoaa)

weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

## Start a plot

```{r ggplot_aes}
ggplot(weather_df, aes(x = tmin, y = tmax))
```

Scatterplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
    geom_point()
```

```{r}
weather_df %>%
    filter(name == "CentralPark_NY") %>%
    ggplot(aes(x = tmin, y = tmax)) +
             geom_point()
```

## More plot options

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name))
```

Add a geom

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name)) +
  geom_smooth(se = FALSE)
```

And even more options...

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.4) +
  geom_smooth(se = FALSE)
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.4) +
  geom_smooth(se = FALSE)
```

Facetting...

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.4) +
  geom_smooth(se = FALSE) +
  facet_grid( ~ name)
```

A more interesting plot!

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name, size = prcp)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  facet_grid(~name)
```

## Univariate plots

Histograms

```{r}
ggplot(weather_df, aes(x = tmax)) +
  geom_histogram()
```

Density plot

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_density(alpha = 0.5)
```

Box plots

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) +
  geom_boxplot()
```

Violin plots

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) +
  geom_violin(aes(fill = name))
```

```{r}
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)
```

## Saving and embedding plots

```{r}
weather_plot = ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 

ggsave("weather_plot.pdf", weather_plot, width = 8, height = 5)
```

